/**
 * Application Error Codes
 * Machine-readable codes for all application errors.
 * Used in API responses and client-side error handling.
 */
export const ERROR_CODES = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_MISSING: 'TOKEN_MISSING',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // User / Registration
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',

  // Password Reset
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  SMTP_NOT_CONFIGURED: 'SMTP_NOT_CONFIGURED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Resource Errors
  COLLEGE_NOT_FOUND: 'COLLEGE_NOT_FOUND',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  ENQUIRY_NOT_FOUND: 'ENQUIRY_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  INSIGHT_NOT_FOUND: 'INSIGHT_NOT_FOUND',

  // Conflict
  SLUG_EXISTS: 'SLUG_EXISTS',
  ALREADY_IN_WISHLIST: 'ALREADY_IN_WISHLIST',
  NOT_IN_WISHLIST: 'NOT_IN_WISHLIST',
  WISHLIST_LIMIT_EXCEEDED: 'WISHLIST_LIMIT_EXCEEDED',

  // Upload
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Database
  DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
